# Generated by Django 5.1.4 on 2025-01-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diario',
            name='tags',
        ),
        migrations.AddField(
            model_name='diario',
            name='tags',
            field=models.ManyToManyField(related_name='diarios', to='diario.tag'),
        ),
    ]
